name: Version Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   id: get_version
                uses: battila7/get-version-action@v2

            -   name: Setup Java & Maven
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '17'
                    cache: maven
                    server-id: central
                    server-username: CENTRAL_USERNAME
                    server-password: CENTRAL_TOKEN

            -   name: Test
                run: mvn test

            -   name: Import GPG
                uses: crazy-max/ghaction-import-gpg@v6
                with:
                    gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                    passphrase: ${{ secrets.GPG_PASSPHRASE }}

            -   name: Publish
                run: mvn clean deploy
                env:
                    CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
                    CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}

            -   name: Release
                uses: softprops/action-gh-release@v1
